// Generated by scripts/fetch-ummahapi.mjs from https://ummahapi.com/api/zakat/info (UmmahAPI, offered as sadaqah jariah) on 2026-10-07. Don't edit by hand.
import type { ZakatInfo } from './zakat';

export const ZAKAT_INFO: ZakatInfo = {
  "definition": "Zakat is the third pillar of Islam — an obligatory annual payment of 2.5% on qualifying wealth held above the nisab threshold for one lunar year.",
  "nisab": {
    "gold": {
      "grams": 85,
      "description": "Nisab based on 85 grams of pure gold (scholarly consensus)."
    },
    "silver": {
      "grams": 595,
      "description": "Nisab based on 595 grams of pure silver. Many scholars prefer this as it benefits more people."
    },
    "note": "The silver nisab is typically lower in monetary value, meaning more Muslims are required to pay. Scholars differ on which to use; consult a local scholar."
  },
  "rate": {
    "general": "2.5% (1/40) on cash, gold, silver, stocks, trade goods, and other investments",
    "agriculture_rain": "10% (Ushr) on crops irrigated by rain or natural water",
    "agriculture_irrigated": "5% on crops requiring artificial irrigation"
  },
  "conditions": [
    "Muslim (Zakat is only obligatory on Muslims)",
    "Sane and adult (Baligh)",
    "Free person (not enslaved)",
    "Owns wealth above the nisab threshold",
    "Wealth held for one full lunar year (hawl) — agricultural produce is exempt from hawl"
  ],
  "eligible_recipients": [
    "The poor (Fuqara)",
    "The destitute (Masakeen)",
    "Zakat administrators",
    "Those whose hearts are to be reconciled (new Muslims, etc.)",
    "Those in bondage or slavery",
    "Those in debt (Gharimeen)",
    "Those striving in the way of Allah (Fi Sabilillah)",
    "The stranded traveler (Ibn al-Sabil)"
  ],
  "zakatable_assets": [
    "Cash and bank savings",
    "Gold and silver (bullion, jewelry not in daily use)",
    "Stocks and shares (calculate based on zakatable portion)",
    "Business inventory and trade goods",
    "Agricultural produce (at harvest)",
    "Livestock (specific nisab and rates apply)",
    "Rental income and investment returns"
  ],
  "non_zakatable_assets": [
    "Primary home",
    "Personal vehicle",
    "Household furniture and personal items",
    "Tools and equipment used in work",
    "Gold and silver jewelry worn daily (scholars differ on this)"
  ],
  "hawl": "The hawl is the lunar year. Zakat becomes due once the nisab has been held for a complete lunar year (approximately 354 days). If wealth drops below nisab during the year and rises again, the year resets.",
  "disclaimer": "This calculator provides an estimate based on common scholarly positions. For personal religious rulings, consult a qualified Islamic scholar (Mufti) in your region.",
  "source": "Based on principles from the four major Sunni schools of law (Hanafi, Maliki, Shafi'i, Hanbali)."
};
