/**
 * Saves UmmahAPI's du'as (https://ummahapi.com/api/duas, offered free as sadaqah jariah) into
 * api/_lib/duas-data.ts, so QuranFlow AI answers from a fixed, reviewed copy instead of a live
 * service. Re-run to refresh, then review the diff:
 *
 *   node scripts/fetch-duas.mjs
 */
import { writeFileSync } from 'node:fs';

const SOURCE = 'https://ummahapi.com/api/duas';
const OUT = new URL('../api/_lib/duas-data.ts', import.meta.url);

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE}: HTTP ${response.status}`);
const { data } = await response.json();

const clean = (s) => String(s ?? '').replace(/\s+/g, ' ').trim();
const seen = new Set();
const duas = [];
for (const d of data.duas) {
  // The same du'a can sit in several categories (each with its own title, so kept), but a few repeat inside one category
  const key = `${d.category}:${clean(d.arabic).replace(/[\u064B-\u065F\u0670\s،,.]/g, '')}`;
  if (!key || seen.has(key)) continue;
  seen.add(key);
  duas.push({
    id: d.id,
    category: d.category,
    title: clean(d.title),
    arabic: clean(d.arabic),
    transliteration: clean(d.transliteration),
    translation: clean(d.translation),
    source: clean(d.source),
    repeat: Number(d.repeat) > 1 ? Number(d.repeat) : 1,
  });
}
const categories = data.categories.map((c) => ({ id: c.id, name: clean(c.name), description: clean(c.description) }));

writeFileSync(
  OUT,
  `// Generated by scripts/fetch-duas.mjs from ${SOURCE} (UmmahAPI, offered as sadaqah jariah) on ${new Date().toISOString().slice(0, 10)}. Don't edit by hand.\n` +
    `import type { Dua, DuaCategory } from './duas';\n\n` +
    `export const DUA_CATEGORIES: DuaCategory[] = ${JSON.stringify(categories, null, 2)};\n\n` +
    `export const DUAS: Dua[] = ${JSON.stringify(duas, null, 2)};\n`,
);
console.log(`${duas.length} du'as (${data.duas.length - duas.length} repeats skipped), ${categories.length} categories → api/_lib/duas-data.ts`);
